[package]
name = "oxidx"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies.windows]
version = "0.56.0"
features = [
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
]
