[package]
name = "oxidx"
version = "0.1.0"
edition = "2021"

[dependencies.bitflags]
version = "2.5.0"

[dependencies.smallvec]
version = "1.13.2"

[dependencies.compact_str]
version = "0.7.1"

[dependencies.windows]
version = "0.56.0"
features = [
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",

    "Win32_Security",
    "Win32_System_Threading",
]
