[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
oxidx = { path = "../../oxidx" }
tracing = "0.1.40"
tracing-subscriber = "0.3.0"
winit = "0.30.2"